# security check action script

name: terraform-security-check
on: [pull_request,push]

jobs:
  tfsec:
    name: server name
    runs-on: ubuntu-latest

    steps:
      - name: clone repository to vertual environment
        uses: actions/checkout@master

      - name: tfsec commentor
        uses: tfsec/tfsec-pr-commenter-action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tfsec_exclude: "AWS018"
      - name: tf security scan
        uses: triat/terraform-security-scan@v2.0.2
        with:
          tfsec_output_format: JSON
          tfsec_exclude: "AWS018"



